home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('login/', views.login_page, name='login_page'),
    path('navegacao/', views.navigation_page, name='navigation_page'),
]

linguica_divina/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('vendas/', include('vendas.urls')),
]

vendas/urls.py
from django.urls import path
from . import views

app_name = "vendas"

urlpatterns = [
    path('', views.display_vendas, name='display_vendas'),
    path('relatorios/', views.display_relatorios, name='display_relatorios'),
    path('register/', views.register_venda, name='register_venda'),
    path('update/<int:id>', views.update_venda, name='update_venda'),
    path('delete/<int:id>', views.delete_venda, name='delete_venda'),
]

home/models.py
from django.db import models

vendas/models.py
from django.db import models
from . import choices

class Venda(models.Model):
    nome_cliente = models.CharField(max_length=50, blank=True, null=True)
    valor_un_kg = models.DecimalField(max_digits=8, decimal_places=2)
    qtd_kgs = models.DecimalField(max_digits=8, decimal_places=2)
    data_venda = models.DateTimeField(auto_now_add=True)
    descricao_venda = models.TextField(default="", blank=True, null=True)
    metodo_pagamento = models.CharField(max_length=10, default=choices.PAYMENT_METHODS[0][0], choices=choices.PAYMENT_METHODS)
    valor_total = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        data_formatada = self.data_venda.strftime('%d/%m/%Y')
        return f'Venda | Cliente: {self.nome_cliente if self.nome_cliente else 'Não Informado'}, Data: {data_formatada}'

home/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(
        label="Usuário",
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'input-field', 'placeholder': 'Digite seu usuário'})
    )
    password = forms.CharField(
        label="Senha",
        widget=forms.PasswordInput(attrs={'class': 'input-field', 'placeholder': 'Digite sua senha'})
    )

vendas/forms.py
from django import forms
from .models import Venda
from . import choices

class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = ['nome_cliente', 'valor_un_kg', 'qtd_kgs', 'descricao_venda', 'metodo_pagamento']
        widgets = {
            'descricao_venda': forms.Textarea(attrs={
                'rows': 4, 
                'cols': 40,
                'class': 'textarea-field',
                }),
            'nome_cliente': forms.TextInput(attrs={
                'class': 'input-field'
            }),
            'valor_un_kg': forms.TextInput(attrs={
                'class': 'input-field'
            }),
            'qtd_kgs': forms.TextInput(attrs={
                'class': 'input-field'
            }),
            'metodo_pagamento': forms.Select(
                attrs={'class': 'choice-field'},
            )
                
        }

class FiltroVendaForm(forms.Form):
    data_inicial = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    data_final = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    metodo_pagamento = forms.ChoiceField(choices=[("", "Todos")] + choices.PAYMENT_METHODS, required=False)

home/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LoginForm

def landing_page(request):

    """
        This view returns the first page of the application
    """

    current_date = datetime.now().strftime("%d/%m/%Y")

    context_ = {
        "current_date": current_date
    }

    return render(request, 'home/landing.html', context_)

@login_required(login_url='home:landing_page')
def navigation_page(request):
    """
        This view returns the navigation page, where you can
        manage the CRUDs
    """
    current_date = datetime.now().strftime("%d/%m/%Y")

    context_ = {
        "current_date": current_date
    }

    return render(request, 'home/navigation.html', context_)

# LOGIN SECTION

def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login realizado com sucesso!')
                return redirect('home:navigation_page')  # Substitua 'home' pela URL desejada
            else:
                messages.error(request, 'Usuário ou senha inválidos.')
    else:
        form = LoginForm()

    return render(request, 'home/login.html', {'form': form})

vendas/views.py
from django.shortcuts import get_object_or_404, render, redirect
from datetime import datetime
from .models import Venda
from .forms import VendaForm, FiltroVendaForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
@login_required(login_url='home:landing_page')
def display_vendas(request):

    vendas = Venda.objects.all()

    search_query = request.GET.get('search', '')
    if search_query:
        vendas = vendas.filter(
        Q(nome_cliente__istartswith=search_query) |
        Q(data_venda__icontains=search_query)
    )

    current_date = datetime.now().strftime("%d/%m/%Y")

    context_ = {
        "current_date": current_date,
        "vendas" : vendas
    }

    return render(request, 'vendas/display.html', context_)
@login_required(login_url='home:landing_page')
def register_venda(request):

    current_date = datetime.now().strftime("%d/%m/%Y")

    if request.method == 'POST':
        form = VendaForm(request.POST)
        if form.is_valid():

            form.save()
            return redirect('vendas:display_vendas')
    
    form = VendaForm()
    
    context_ = {
        "current_date": current_date,
        "form": form
    }

    return render(request, 'vendas/register.html', context_)
@login_required(login_url='home:landing_page')
def update_venda(request, id):

    current_date = datetime.now().strftime("%d/%m/%Y")

    venda = get_object_or_404(Venda, id=id)

    if request.method == 'POST':
        form = VendaForm(request.POST, instance=venda)
        if form.is_valid():

            form.save()
            return redirect('vendas:display_vendas')
    
    form = VendaForm(instance=venda)
    
    context_ = {
        "current_date": current_date,
        "form": form
    }

    return render(request, 'vendas/register.html', context_)

@login_required(login_url='home:landing_page')
def delete_venda(request, id):

    venda = get_object_or_404(Venda, id=id)

    venda.delete()
    return redirect('vendas:display_vendas')
    
@login_required(login_url='home:landing_page')    
def display_relatorios(request):
    vendas = Venda.objects.all() 
    form = FiltroVendaForm(request.GET or None)

    if form.is_valid():

        data_inicial = form.cleaned_data.get('data_inicial')
        data_final = form.cleaned_data.get('data_final')
        metodo_pagamento = form.cleaned_data.get('metodo_pagamento')

        if data_inicial:
            vendas = vendas.filter(data_venda__gte=data_inicial)
        if data_final:
            data_final = datetime.combine(data_final, datetime.max.time())
            vendas = vendas.filter(data_venda__lte=data_final)
        if metodo_pagamento:
            print(metodo_pagamento)
            vendas = vendas.filter(metodo_pagamento=metodo_pagamento)

    somatorio_vendas = 0.0

    for venda in vendas:

        somatorio_vendas += float(venda.valor_total)

    context_ = {
        'vendas': vendas,
        'form': form,
        'somatorio': f"{float(somatorio_vendas):,.2f}".replace(",", "X").replace(".", ",").replace("X", "."),
    }

    return render(request, 'vendas/relatorios.html', context=context_)

home/templates/home/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class="content-box-landingpage">
        <div class="left-container-landingpage">
            <h1 style="width: 60%; font-size: 3rem;">Seja bem-vinda(o) ao Sistema de Gerenciamento da Linguiça Dona Alvina</h1>
            <a href="{% url 'home:login_page' %}" class="login-btn">ENTRAR</a>
        </div>
        <div style="width: 60%;">
            <img class="logo-img-landingpage" width="400" src="{% static 'images/logo-dona-alvina.png' %}" alt="">
        </div>
    </main>
{% endblock content %}

home/templates/home/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="login-container">
    <h2 class="login-title">Login</h2>
    <form method="post" class="login-form">
        {% csrf_token %}

        <h2>Usuário:</h2>
        <p>{{ form.username }}</p>
        <h2>Senha:</h2>
        <p>{{ form.password }}</p>
        <button type="submit" class="login-button">Entrar</button>
    </form>

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="message {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock content %}

home/templates/home/navigation.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'home:landing_page' %}" class="return-btn">VOLTAR</a>
<main class="navigation-main">
    <div class="module-container">
        <a href="{% url 'vendas:display_vendas' %}">Gerenciar Vendas</a>
        <p>Neste módulo você conseguirá adicionar, atualizar, visualizar ou deletar vendas</p>
    </div>
    <div class="module-container">
        <a href="{% url 'vendas:display_relatorios' %}">Relatórios</a>
        <p>Neste módulo você terá acesso a relatórios detalhados de suas vendas</p>
    </div>
</main>
{% endblock content %}

vendas/templates/vendas/display.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<a href="{% url 'home:navigation_page' %}" class="return-btn">VOLTAR</a>
<main class="display-vendas-main">
    <h2 style="font-family: Arial, Helvetica, sans-serif; margin-top: 20px; color: #7c3e30; font-size: 2.5rem;">Vendas</h2>
    <form method="get" action="{% url 'vendas:display_vendas' %}">
        <input class="search-input" type="text" name="search" placeholder="Pesquisar por nome ou data..." />
        <button class="search-btn" type="submit">Pesquisar</button>
    </form>    
    <div class="vendas-container">
        <a href="{% url 'vendas:register_venda' %}" class="add-register-button">Adicionar Venda</a>
        {% if vendas %}
            {% for venda in vendas %}
                <div class="venda-module">
                    <a href="#">
                        {{ venda | default:"Nome não registrado" }}
                    </a>
                    <button onclick="abrirModal({{ venda.id }})">Ver Detalhes</button>
                </div>
                <div id="modalVenda{{ venda.id }}" class="modal">
                    <div class="modal-content">
                        <span class="close" onclick="fecharModal({{ venda.id }})">&times;</span> 
                        <p class="modal-text"><strong>Cliente:</strong> {{ venda.nome_cliente }}</p>
                        <p class="modal-text"><strong>Método Pagamento:</strong> {{ venda.metodo_pagamento }}</p>
                        <p class="modal-text"><strong>Valor por kg:</strong> {{ venda.valor_un_kg }}</p>
                        <p class="modal-text"><strong>Quantidade:</strong> {{ venda.qtd_kgs }}</p>
                        <p class="modal-text"><strong>Data:</strong> {{ venda.data_venda|date:"d/m/Y" }}</p>
                        <p class="modal-text"><strong>Descrição:</strong> {{ venda.descricao_venda }}</p>
                        <p class="modal-text" style="margin-bottom: 20px;"><strong>Valor Total:</strong> {{ venda.valor_total }}</p>
                        <a class="modal-btn-edit" href="{% url 'vendas:update_venda' venda.id %}">Editar Venda</a>
                        <a class="modal-btn-delete" href="{% url 'vendas:delete_venda' venda.id %}">Excluir Venda</a>
                    </div>
                </div>
            {% endfor %}

        {% else %}
                
            <p style="font-family: Arial, Helvetica, sans-serif; color: #7c3e30; font-size: 1.5rem; margin-top: 10px;">Nenhuma venda encontrada...</p>

        {% endif %}
    </div>
</main>
{% endblock content %}

vendas/templates/vendas/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="register-container">
    <form method="POST">
        {% csrf_token %}
        
        <h2>Nome Cliente:</h2>
        <p>{{ form.nome_cliente }}</p>
        <h2>Método Pagamento:</h2>
        <p>{{ form.metodo_pagamento }}</p>
        <h2>Valor Unit.(kg):</h2>
        <p>{{ form.valor_un_kg }}</p>
        <h2>Quantidade(kg):</h2>
        <p>{{ form.qtd_kgs }}</p>
        <h2>Descrição:</h2>
        <p>{{ form.descricao_venda }}</p>

        <div class="btn-wrapper">
            <button type="submit" class="save-venda-btn">Salvar Venda</button>
            <a href="{% url 'vendas:display_vendas' %}" class="cancel-venda-btn">Cancelar</a>
        </div>
    </form>
</div>

{% endblock content %}

vendas/templates/vendas/relatorios.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'home:navigation_page' %}" class="return-btn">VOLTAR</a>
<h2 class="relatorios-title">Relatório de Vendas</h2>

<form method="get" class="filter-form">
    {{ form.as_p }}
    <button type="submit" class="filter-button">Filtrar</button>
</form>

<div class="relatorios-container">
    <h3 class="valor-total">Valor total: {{ somatorio }}</h3>
    {% for venda in vendas %}
        <div class="relatorio-card">
            <p><strong>Cliente:</strong> {{ venda.nome_cliente }}</p>
            <p><strong>Data:</strong> {{ venda.data_venda|date:"d/m/Y" }}</p>
            <p><strong>Método Pagamento:</strong> {{ venda.metodo_pagamento }}</p>
            <p><strong>Valor Total:</strong> R$ {{ venda.valor_total }}</p>
        </div>
    {% empty %}
        <p style="font-family: Arial, Helvetica, sans-serif; color: #7c3e30; font-size: 1.5rem; margin-top: 10px;">Nenhuma venda encontrada para os critérios selecionados.</p>
    {% endfor %}
</div>
{% endblock %}